version: "3"

services:
    api:
        build:
            context: ./sa_api
            dockerfile: Dockerfile
        image: backend-api
        container_name: backend-api
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: api
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./backend-api:/var/www
            - ./backend-api/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - api-network

    api-db:
        image: mysql:5.7.22
        container_name: backend-api-db
        restart: unless-stopped
        tty: true
        command: --disable-partition-engine-check
        ports:
            - 3306:3306
        environment:
            MYSQL_DATABASE: tetris_db
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - dbdata:/var/lib/mysql
            - ./backend-api/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            - api-network

networks:
    api-network:
        driver: bridge

volumes:
    dbdata:
        driver: local
